version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment: 
      - DOCKER_BUILDKIT=1
    volumes:
      - ~/.ssh:/root/.ssh
networks: 
  default:
    name: prototypetesting_default